### ISSUE TITLE
Home button action

### ISSUE THREAD

**Issue by Smart1109** [vasyl91/muse-sleep-tracker-and-arduino-light-therapy#2]
Hi,

I am working on your react-native-android-alarms and it's useful.
I look through other node modules but they didn't work.

I can set, activate and stop alarm.
But if I click the home button, the alarm doesn't work.

Can you explain me how to figure this out?

**Comment by vasyl91** [comment]
Hi, 
You mean that if you minimize the app by clicking home button the alarm won't trigger? If so, then probably app is being silently killed whilst in background. Check some settings to let it function in background.

**Comment by Smart1109** [comment]
Yes, that's my problem.

Is there any function to work in background?

**Comment by vasyl91** [comment]
Hmm, the app is asking to turn off battery optimisation on first start. Check it in android settings if the app is marked as `not optimised`. If you're using some third party apps that clear memory then maybe there is the issue. App is also being killed after clearing memory manually, so don't do that if you want to use it. Generally it depends on your settings and probably on android version, you'll have to google it.

**Comment by Smart1109** [comment]
I see

Thanks for your care

**Comment by vasyl91** [comment]
You're welcome ;)
